apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: vhostnet
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vhostnet
  networkNamespace: vhostnet
  trust: "on"
  spoofChk: "off"
