apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vhostnet
  name: vhostnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhostnet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vhostnet
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [
            {
              "name": "vhostnet"
            },
            {
              "name": "vhostnet"
            },
            {
              "name": "vhostnet"
            },
            {
              "name": "vhostnet"
            }
          ]
    spec:
      containers:
      - command:
        - "/bin/bash"
        - "-x"
        - "/entrypoint/vhostnet.sh"
        image: quay.io/akaris/testpmd:latest
        imagePullPolicy: IfNotPresent
        name: vhostnet
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint
        - mountPath: /dev/hugepages
          name: hugepage
          readOnly: False
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - NET_BIND_SERVICE
          privileged: true
        resources:
          requests:
            memory: 2000Mi
            hugepages-1Gi: 16Gi
            cpu: '16'
          limits:
            hugepages-1Gi: 16Gi
            cpu: '16'
            memory: 2000Mi
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint
          defaultMode: 0755
      - name: hugepage
        emptyDir:
          medium: HugePages
